### ISSUE TITLE
discussions are disabled, but most issue templates link to discussions

### ISSUE THREAD

**Issue by TayouVR** [refiaa/VRChatFriendShipVisualizer#5]
### VRChat Friend Network Version

--

### Node.js Version

--

### Operating System

--

### Browser & Version

--

### Reproduction Steps

1. go to issues tab
2. click "new"
3. click any of the templates besides "Bug Report"

### Expected Behavior

I can suggest e.g. a feature

### Actual Behavior

404

**Comment by refiaa** [comment]
gonna modify it thx!

**Comment by refiaa** [comment]
now i able discussion, you can use it now .

**Comment by TayouVR** [comment]
thx <3
